= Автоматическое управление памятью

[pluses]
*  Освобождает от рутины
ручного управления памятью
* снижает количество
труднообнаружимых ошибок:
** Висящие ссылки исчезают как класс
** Вероятность утечек памяти снижается
* Упрощает программные интерфейсы. При реализации программы всегда задается "бюджет сложности" и с простым интерфейсом его можно потратить на что-то более полезное. У систем с ручным управлением много ресурсов уходить на это самое управление.

== Классификация автоматического управления памятью

=== Автоматическое освобождение (automatic memory reclamation)

* Надстройка над ручной системой отведения
памяти (пулами, кучей или их комбинацией). Надстроццка в виде библиотечного расширения, которое автоматически вызывает free. Т.к. это библиотека, она не требует поддержки со стороны компилятора


=== Сборка мусора (garbage collection)

* Отдельная система управления памятью,
вычисляющая достижимость объектов
просмотром ссылок
* Часто способна перемещать объекты для
снижения внешней фрагментации

Есть расхождение в терминах: иногда любое автоматическое управление
называют сборкой мусора, а собственно
сборку — *сканирующей* сборкой мусора


