= Критерии сравнения систем управления памятью

==  Замедление выполнения приложения (execution time overhead)
Иногда доля времени, проводимая приложением в коде системы управления памятью (mark/cons ratio)

Не вполне корректная мера — часть работы управления памятью может быть перенесена в код приложения и наоборотю. 

Часть логики сборщика мусора может быть реализована в интерпретатора. И наоборот,  Например, управление памятью может повышать локальность, уменьшая частоту кэш-промахов приложения

== Затраты памяти (space overhead)
Доля памяти, недоступной приложению, во всей отведенной для него ОС памяти

Иногда вводят как коэффициент фрагментации - отношение объемов недоступной и доступной приложению памяти

== Распределение длительности пауз
● В идеале каждый вызов системы управления
памятью должен обрабатываться за фиксированное
и притом малое время
● Чуть хуже, если время обработки запроса
пропорционально размеру объекта
● Все равно все поля объекта нужно
инициализировать
● Контрпример - отведение стека в виде массива не
требует инициализации его тела
● Недостаточно ограничить длительность каждого
вызова системы управления памятью
● Нужно, чтобы приложение успело выполнить
достаточно работы в промежутках
● Minimal Mutator Utilization (MMU) — минимальная
доля времени, проведенная в коде приложения, в
интервалах заданной длительности
● Bounded Mutator Utilization (BMU) — минимальная
доля времени, проведенного в коде приложения, в
интервалах большей или заданной длительности