= Управление памятью в пулах

Пул — область памяти, в пределах которой
организуется распределение в соответствии с некоторой специфической дисциплиной

== Область памяти пула

* Может отводиться статически, ОС, в другом пуле
или куче

* Может быть непрерывной или кусочной

* Может быть фиксированного или изменяемого
объема

== Примеры дисциплин

* Стек — отведение с дисциплиной LIFO

* Отведение и освобождение объектов одинакового
размера

* Отведение объектов со сходными временами жизни (scoped memory)

* Некоторые контейнеры содержат пулы для хранения своих элементов (чтобы обрабатывать эффективнее, чем в обычной памяти)

== Преимущества специализированного распределения памяти

===  Скорость

* Для отведения достаточно нескольких машинных инструкций

* Единовременное освобождение всего пула

=== Предсказуемость
* Худший случай не сильно хуже среднего

* Из-за простоты реализации легко поддается анализу

=== Минимизация внутренней фрагментации 
Заголовков объектов, служебных структур, потерь на округление размера

=== Минимизация внешней фрагментации
Отведен участок памяти, в котором лежать некоторое числа объектов. Между ними могут быть дыры, в которые очередной объект получить нельзя.


Отведение памяти в пулах — это оптимизация

* Не следует тратить на нее усилия без необходимости

* Современные реализации отведения памяти в куче достаточно хороши для многих применений